// SPDX-License-Identifier: GPL-2.0-or-later
#ifndef HPLJ_ERROR_H
#define HPLJ_ERROR_H

enum hplj_error_category {
  HPLJ_ERROR_NONE,
  HPLJ_ERROR_INVALID_STATE,
  HPLJ_ERROR_UNSUPPORTED_DEVICE,
  HPLJ_ERROR_DEVICE_ACCESS_DENIED,
  HPLJ_ERROR_DEVICE_PROTOCOL,
  HPLJ_ERROR_DEVICE_DISCONNECTED,
  HPLJ_ERROR_DEVICE_TIMEOUT,
  HPLJ_ERROR_TRANSFER_INCOMPLETE,
  HPLJ_ERROR_FIRMWARE_MISSING,
  HPLJ_ERROR_FIRMWARE_AFFIRMATION_REQUIRED,
  HPLJ_ERROR_FIRMWARE_UNSUPPORTED,
  HPLJ_ERROR_FIRMWARE_CORRUPT,
  HPLJ_ERROR_FIRMWARE_STORAGE_FAILED,
  HPLJ_ERROR_FIRMWARE_TRANSFER_FAILED,
  HPLJ_ERROR_FIRMWARE_UNVERIFIED,
  HPLJ_ERROR_RASTER_INVALID,
  HPLJ_ERROR_CANCELLED,
  HPLJ_ERROR_ENCODING_FAILED,
  HPLJ_ERROR_QUEUE_UNAVAILABLE,
  HPLJ_ERROR_MEDIA_EMPTY,
  HPLJ_ERROR_MANUAL_FEED_REQUIRED,
  HPLJ_ERROR_COVER_OPEN,
  HPLJ_ERROR_DEVICE_FAULT,
  HPLJ_ERROR_CATEGORY_COUNT,
};

enum hplj_retry_safety {
  HPLJ_RETRY_SAFE_AUTOMATIC,
  HPLJ_RETRY_EXPLICIT,
  HPLJ_RETRY_NEVER,
};

enum hplj_human_action {
  HPLJ_ACTION_NONE,
  HPLJ_ACTION_IMPORT_FIRMWARE,
  HPLJ_ACTION_AFFIRM_LAWFUL_ACQUISITION,
  HPLJ_ACTION_SELECT_SUPPORTED_FIRMWARE,
  HPLJ_ACTION_REACQUIRE_FIRMWARE,
  HPLJ_ACTION_RETRY_FIRMWARE_IMPORT,
  HPLJ_ACTION_RECONNECT_AND_RETRY_FIRMWARE,
  HPLJ_ACTION_POWER_CYCLE_PRINTER,
  HPLJ_ACTION_RETRY_UNINSTALL,
  HPLJ_ACTION_RECONNECT_PRINTER,
  HPLJ_ACTION_RETRY_JOB,
  HPLJ_ACTION_CORRECT_RASTER,
  HPLJ_ACTION_LOAD_MEDIA,
  HPLJ_ACTION_LOAD_MANUAL_FEED,
  HPLJ_ACTION_CLOSE_COVER,
  HPLJ_ACTION_CLEAR_DEVICE_FAULT,
  HPLJ_ACTION_RETRY_QUEUE,
};

struct hplj_error {
  enum hplj_error_category category;
  enum hplj_retry_safety retry;
  enum hplj_human_action action;
  const char *detail;
};

struct hplj_error hplj_error_make(enum hplj_error_category category,
                                  enum hplj_retry_safety retry,
                                  enum hplj_human_action action,
                                  const char *detail);
const char *hplj_error_category_name(enum hplj_error_category category);

#endif
