#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1 && tput clear 2>/dev/null; then
    return 0
  fi
  printf '\033[2J\033[3J\033[H'
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

ROOT=$(cd "$(dirname "$0")/.." && pwd)
INSTALLER="$ROOT/scripts/personal_install.py"
SEALER="$ROOT/scripts/seal_lifecycle_evidence.py"
INTERRUPTER="$ROOT/scripts/interrupt_lifecycle_validation.py"
MATRIX="$ROOT/validation/capability-matrix.json"
RUN_ID="issue-28-$(date -u +%Y%m%dT%H%M%SZ)"
EVIDENCE_ROOT="$ROOT/validation/runs/$RUN_ID"
LOG="$EVIDENCE_ROOT/sanitized.log"
SUMMARY="$EVIDENCE_ROOT/summary.txt"
TEST_USER="hplj1020-validation"
TEST_REAL_NAME="HP LJ 1020 Validation Account"
SERVICE_LABEL="com.bartekpapierski.hplj1020.service"
QUEUE="HP_LaserJet_1020"
INSTALL_ROOT="/Library/Application Support/HP-LJ-1020"
PLIST="/Library/LaunchDaemons/$SERVICE_LABEL.plist"
EXPECTED_VERSION="26.7.1"
EXPECTED_BUILD="25G241"
FIRMWARE_SOURCE="/Library/Application Support/HP-LJ-1020/firmware/active/contents"
FIRMWARE_SNAPSHOT=""
RESTORE_PRINTING=1
while (( $# )); do
  case "$1" in
    --firmware-source)
      (( $# >= 2 )) || { printf 'Missing firmware source argument\n' >&2; exit 2; }
      FIRMWARE_SOURCE="$2"
      shift 2
      ;;
    --leave-uninstalled) RESTORE_PRINTING=0; shift ;;
    *) printf 'Unknown lifecycle option\n' >&2; exit 2 ;;
  esac
done
SOURCE_COMMIT=""
LOCK_SHA=$(shasum -a 256 "$ROOT/dependencies.lock.json" | awk '{print $1}')
PRINTER_SERIAL_SHA=""
SOURCE_COMMIT=$(git -C "$ROOT" rev-parse HEAD)
TEST_PAGE="$ROOT/validation/fixtures/lifecycle-calibration.pdf"
SOURCE_DOCUMENT_SHA=$(shasum -a 256 "$TEST_PAGE" | awk '{print $1}')
UNRELATED_BEFORE=""
CUPSD_SHA_BEFORE=""
CUPS_CONFIG_SHA_BEFORE=""
CUPS_LAUNCHD_SHA_BEFORE=""
LIFECYCLE_CYCLES=0
OBSERVED_PAGES=0
STARTED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
PRIVILEGE_MONITOR_PID=""
SEALED=0
VALIDATION_ACCOUNT_OWNED=0
VALIDATION_GROUP_CREATED=0
VALIDATION_USER_CREATED=0
ERROR_LINE=unknown
DOCK_LOCATION=""
SCALE_ERROR_PERCENT=0
MAXIMUM_FIDUCIAL_DISPLACEMENT_MM=0
ARTIFACT_SHA="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
BUILT_AT="$STARTED_AT"
XCODE_BUILD=$(xcodebuild -version 2>/dev/null | tr '\n' ' ')
COMPILER=$(cc --version | sed -n '1p')
SDK_BUILD=$(xcrun --show-sdk-build-version)
DEPLOYMENT_TARGET="unavailable"

mkdir -p "$EVIDENCE_ROOT"
chmod 700 "$EVIDENCE_ROOT"
: >"$LOG"
: >"$SUMMARY"

sanitize() {
  sed \
    -e "s|$ROOT|\$REPOSITORY|g" \
    -e "s|/Users/[^/[:space:]]*|/Users/REDACTED|g" \
    -e "s|$TEST_USER|validation-account|g" \
    -e 's|_hplj1020|dedicated-account|g' \
    -e "s|${USER:-unknown}|local-user|g" \
    -e 's/request id is [^[:space:]]*/request accepted/g'
}

record() {
  printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" | sanitize | tee -a "$LOG"
}

run_recorded() {
  record "run: $*"
  "$@" 2>&1 | sanitize | tee -a "$LOG"
}

fail() {
  record "FAILED: $*"
  warn "$*"
  remove_validation_account || record "temporary validation account cleanup incomplete"
  seal_run failed "$*" || true
  warn "Evidence retained at $EVIDENCE_ROOT"
  exit 1
}

seal_run() {
  local result="$1" reason="$2"
  local args=(
    --evidence-root "$EVIDENCE_ROOT"
    --matrix "$MATRIX"
    --run-id "$RUN_ID"
    --started-at "$STARTED_AT"
    --result "$result"
    --reason "$reason"
    --source-commit "$SOURCE_COMMIT"
    --dependency-lock-sha256 "$LOCK_SHA"
    --source-document-sha256 "$SOURCE_DOCUMENT_SHA"
    --lifecycle-cycles "$LIFECYCLE_CYCLES"
    --observed-pages "$OBSERVED_PAGES"
    --macos-version "$EXPECTED_VERSION"
    --macos-build "$EXPECTED_BUILD"
    --scale-error-percent "$SCALE_ERROR_PERCENT"
    --maximum-fiducial-displacement-mm "$MAXIMUM_FIDUCIAL_DISPLACEMENT_MM"
    --artifact-sha256 "$ARTIFACT_SHA"
    --built-at "$BUILT_AT"
    --xcode-build "$XCODE_BUILD"
    --compiler "$COMPILER"
    --sdk-build "$SDK_BUILD"
    --deployment-target "$DEPLOYMENT_TARGET"
  )
  (( SEALED == 0 )) || return 0
  stop_privilege_monitor
  [[ -n "$PRINTER_SERIAL_SHA" ]] &&
    args+=(--printer-serial-sha256 "$PRINTER_SERIAL_SHA")
  python3 "$SEALER" "${args[@]}"
  SEALED=1
}

stop_privilege_monitor() {
  if [[ -n "$PRIVILEGE_MONITOR_PID" ]]; then
    kill "$PRIVILEGE_MONITOR_PID" 2>/dev/null || true
    wait "$PRIVILEGE_MONITOR_PID" 2>/dev/null || true
    PRIVILEGE_MONITOR_PID=""
  fi
}

assert_privilege_monitor() {
  [[ ! -e "$EVIDENCE_ROOT/privilege-violation.txt" ]] || fail "a product process ran as root"
  [[ ! -e "$EVIDENCE_ROOT/privilege-monitor-failure.txt" ]] || fail "privilege monitoring failed; root execution was not established"
}

start_privilege_monitor() {
  local rows root_rows status
  (
    while true; do
      status=0
      rows=$(product_process_rows 2>/dev/null) || status=$?
      root_rows=$(awk 'NF == 4 && $1 == "0" {
        printf "uid=0 pid=%s parentPid=%s role=%s\n", $2, $3, $4
      }' <<<"$rows")
      if [[ -n "$root_rows" ]]; then
        printf 'root product process observed at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          >"$EVIDENCE_ROOT/privilege-violation.txt"
        printf '%s\n' "$root_rows" >>"$EVIDENCE_ROOT/privilege-violation.txt"
        exit 1
      fi
      if (( status != 0 )); then
        printf 'process snapshot failed at %s status=%s\n' \
          "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$status" \
          >"$EVIDENCE_ROOT/privilege-monitor-failure.txt"
        exit 1
      fi
      sleep 0.2
    done
  ) &
  PRIVILEGE_MONITOR_PID=$!
}

on_exit() {
  local status=$?
  stop_privilege_monitor
  if (( status != 0 && SEALED == 0 )); then
    if (( VALIDATION_ACCOUNT_OWNED )); then
      remove_validation_account || record "temporary validation account cleanup incomplete"
    fi
    seal_run failed "unexpected wizard exit at line $ERROR_LINE" || true
  fi
  if [[ -n "$FIRMWARE_SNAPSHOT" ]]; then
    warn "Private firmware recovery copy retained outside the evidence bundle: $FIRMWARE_SNAPSHOT/contents"
    warn "Do not upload that file. A retry can use --firmware-source with that private file."
  fi
}

trap 'ERROR_LINE=$LINENO' ERR
trap on_exit EXIT

account_matches() {
  local user_record group_record uid gid user_gid home shell real_name
  user_record=$(dscacheutil -q user -a name "$TEST_USER") || return 1
  group_record=$(dscacheutil -q group -a name "$TEST_USER") || return 1
  uid=$(awk '$1 == "uid:" {print $2; exit}' <<<"$user_record")
  user_gid=$(awk '$1 == "gid:" {print $2; exit}' <<<"$user_record")
  gid=$(awk '$1 == "gid:" {print $2; exit}' <<<"$group_record")
  home=$(awk '$1 == "dir:" {print $2; exit}' <<<"$user_record")
  shell=$(awk '$1 == "shell:" {print $2; exit}' <<<"$user_record")
  real_name=$(awk 'index($0, "gecos: ") == 1 {print substr($0, 8); exit}' <<<"$user_record")
  [[ "$uid" =~ ^[0-9]+$ && "$uid" -ge 550 && "$uid" -le 599 ]] &&
    [[ "$user_gid" == "$gid" && "$home" == "/var/empty" ]] &&
    [[ "$shell" == "/usr/bin/false" && "$real_name" == "$TEST_REAL_NAME" ]]
}

next_validation_id() {
  local candidate
  for ((candidate=599; candidate>=550; candidate--)); do
    if ! dscacheutil -q user -a uid "$candidate" | grep -q '^name:' &&
       ! dscacheutil -q group -a gid "$candidate" | grep -q '^name:'; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 1
}

create_validation_account() {
  local account_id
  if id "$TEST_USER" >/dev/null 2>&1; then
    account_matches || fail "refusing colliding validation account"
    VALIDATION_ACCOUNT_OWNED=1
    return
  fi
  if dscacheutil -q group -a name "$TEST_USER" | grep -q '^name:'; then
    fail "refusing colliding validation group without matching account"
  fi
  account_id=$(next_validation_id) || fail "no free validation account ID"
  sudo dscl . -create "/Groups/$TEST_USER"
  VALIDATION_GROUP_CREATED=1
  VALIDATION_ACCOUNT_OWNED=1
  sudo dscl . -create "/Groups/$TEST_USER" PrimaryGroupID "$account_id"
  sudo dscl . -create "/Groups/$TEST_USER" Password '*'
  sudo dscl . -create "/Users/$TEST_USER"
  VALIDATION_USER_CREATED=1
  sudo dscl . -create "/Users/$TEST_USER" UniqueID "$account_id"
  sudo dscl . -create "/Users/$TEST_USER" PrimaryGroupID "$account_id"
  sudo dscl . -create "/Users/$TEST_USER" RealName "$TEST_REAL_NAME"
  sudo dscl . -create "/Users/$TEST_USER" NFSHomeDirectory /var/empty
  sudo dscl . -create "/Users/$TEST_USER" UserShell /usr/bin/false
  sudo dscl . -create "/Users/$TEST_USER" IsHidden 1
  sudo dscl . -create "/Users/$TEST_USER" Password '*'
  if dseditgroup -o checkmember -m "$TEST_USER" admin 2>/dev/null | grep -q 'yes'; then
    fail "temporary validation account unexpectedly belongs to admin"
  fi
  VALIDATION_ACCOUNT_OWNED=1
  record "temporary non-admin validation account created"
}

remove_validation_account() {
  (( VALIDATION_ACCOUNT_OWNED )) || return 0
  if (( VALIDATION_USER_CREATED )) || id "$TEST_USER" >/dev/null 2>&1; then
    if (( ! VALIDATION_USER_CREATED )); then
      account_matches || return 1
    fi
    sudo dscl . -delete "/Users/$TEST_USER"
    VALIDATION_USER_CREATED=0
  fi
  if (( VALIDATION_GROUP_CREATED )) || dscacheutil -q group -a name "$TEST_USER" | grep -q '^name:'; then
    sudo dscl . -delete "/Groups/$TEST_USER"
    VALIDATION_GROUP_CREATED=0
  fi
  VALIDATION_ACCOUNT_OWNED=0
  record "temporary validation account removed"
}

product_process_rows() {
  # uid and ucomm share the kernel snapshot. command arguments are fetched
  # later: a launchd child can exec between those reads, mixing pre-exec root
  # credentials with the service's post-exec arguments.
  ps -axo uid=,pid=,ppid=,ucomm=,command= | awk \
    -v provider="$INSTALL_ROOT/HP-LJ-1020.app/Contents/MacOS/hplj1020" \
    -v supervisor="$INSTALL_ROOT/HP-LJ-1020.app/Contents/Resources/hplj1020-service-supervisor" '
      {
        command=$0
        sub(/^[[:space:]]*[0-9]+[[:space:]]+[0-9]+[[:space:]]+[0-9]+[[:space:]]+[^[:space:]]+[[:space:]]+/, "", command)
        if ($4 == "hplj1020" &&
            (command == provider || index(command, provider " ") == 1)) {
          print $1, $2, $3, "provider"
        } else if (($4 == "bash" || $4 == "sh") &&
            (command == supervisor || index(command, supervisor " ") == 1 ||
            command == "/bin/bash " supervisor || command == "bash " supervisor ||
            command == "/bin/sh " supervisor)) {
          print $1, $2, $3, "supervisor"
        }
      }
    '
}

product_processes_are_unprivileged() {
  local rows
  rows=$(product_process_rows)
  [[ -n "$rows" ]] || return 1
  if awk '$1 == 0 {exit 1}' <<<"$rows"; then
    awk '{printf "observed_product_process_uid=%s\n", $1}' <<<"$rows" | tee -a "$LOG"
    return 0
  fi
  return 1
}

verify_installed_boundaries() {
  assert_privilege_monitor
  run_recorded python3 "$INSTALLER" status
  product_processes_are_unprivileged || fail "service or supervisor missing, or running as root"
  sudo plutil -extract UserName raw "$PLIST" | grep -qx '_hplj1020' ||
    fail "LaunchDaemon does not declare the dedicated account"
  if sudo lsof -nP -iTCP:8631 -sTCP:LISTEN | awk 'NR > 1 {print $9}' | grep -Ev '^(127\.0\.0\.1|\[::1\]):8631$' >/dev/null; then
    fail "port 8631 has a non-loopback listener"
  fi
  sudo lsof -nP -iTCP:8631 -sTCP:LISTEN | sanitize | tee -a "$LOG"
  lpstat -p "$QUEUE" >/dev/null 2>&1 || fail "standard queue is absent"
  if sudo find "$INSTALL_ROOT" -type f \( -iname '*helper*' -o -perm -4000 \) -print | grep -q .; then
    fail "installed privileged helper or setuid file detected"
  fi
  if sudo find /Library/PrivilegedHelperTools /Library/LaunchDaemons -maxdepth 1 \
      -iname '*hplj1020*' ! -path "$PLIST" -print 2>/dev/null | grep -q .; then
    fail "unexpected product privileged helper or LaunchDaemon detected"
  fi
  record "service identity, loopback listener, queue, and no-helper checks passed"
}

submit_non_admin_job() {
  local result
  # The invoking account opens the public fixture; lp runs non-admin outside
  # the private home directory and receives only its bytes, without a filename.
  result=$(
    cd /private/tmp
    sudo -u "$TEST_USER" env HOME=/var/empty \
      lp -d "$QUEUE" -o media=iso_a4_210x297mm -o print-scaling=none < "$TEST_PAGE" 2>&1
  ) || fail "non-admin queue submission failed"
  printf '%s\n' "$result" | sanitize | tee -a "$LOG"
  if ! confirm "Did exactly one A4 calibration page emerge? Keep it for ruler measurements at the end."; then
    fail "physical print observation failed"
  fi
  OBSERVED_PAGES=$((OBSERVED_PAGES + 1))
  record "non-admin submission and physical output observed as passed"
}

preserve_private_firmware() {
  sudo /bin/test -f "$FIRMWARE_SOURCE" &&
    sudo /bin/test ! -L "$FIRMWARE_SOURCE" || fail "private firmware source is unavailable"
  [[ "$(sudo stat -f %z "$FIRMWARE_SOURCE")" == 128999 ]] || fail "private firmware source size is not supported"
  FIRMWARE_SNAPSHOT=$(mktemp -d /private/tmp/hplj1020-lifecycle-firmware.XXXXXX)
  chmod 700 "$FIRMWARE_SNAPSHOT"
  sudo /usr/bin/install -o "$(id -u)" -g "$(id -g)" -m 600 \
    "$FIRMWARE_SOURCE" "$FIRMWARE_SNAPSHOT/contents"
  [[ "$(shasum -a 256 "$FIRMWARE_SNAPSHOT/contents" | awk '{print $1}')" == \
     9a6d03c858d9cf64ba86fdbe6cf0beec1297d2e45e606162b19f3857efae4ff4 ]] ||
    fail "private firmware source is not the supported exact image"
  record "supported firmware preserved in isolated private recovery storage; no payload retained in evidence"
}

import_private_firmware() {
  (
    cd /private/tmp
    sudo -u _hplj1020 "$INSTALL_ROOT/HP-LJ-1020.app/Contents/MacOS/hplj1020" \
      --import-firmware --firmware "$INSTALL_ROOT/firmware" \
      --source "HP HPLIP 3.26.4; previously accepted private local copy" \
      --affirm-lawful-acquisition < "$FIRMWARE_SNAPSHOT/contents"
  )
}

install_product() {
  if [[ -e "$INSTALL_ROOT" || -e "$PLIST" ]]; then
    run_recorded python3 "$INSTALLER" disable --apply --yes || fail "pre-build service pause failed"
  fi
  run_recorded python3 "$INSTALLER" install --apply --yes || fail "install failed"
  import_private_firmware 2>&1 | sanitize | tee -a "$LOG" || fail "private firmware re-import failed"
  record "supported private firmware re-imported after installation"
  if [[ "$DEPLOYMENT_TARGET" == unavailable ]]; then
    ARTIFACT_SHA=$(shasum -a 256 "$ROOT/build/hplj1020" | awk '{print $1}')
    BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    DEPLOYMENT_TARGET=$(otool -l "$ROOT/build/hplj1020" | awk '
      $1 == "cmd" && $2 == "LC_BUILD_VERSION" {build=1}
      build && $1 == "minos" {print $2; exit}
    ')
    [[ -n "$DEPLOYMENT_TARGET" ]] || fail "built artifact deployment target is unavailable"
  fi
  verify_installed_boundaries
}

uninstall_product() {
  run_recorded python3 "$INSTALLER" uninstall || fail "uninstall preview failed"
  run_recorded python3 "$INSTALLER" uninstall --apply --yes || fail "uninstall failed"
  [[ ! -e "$INSTALL_ROOT" && ! -e "$PLIST" ]] || fail "product artifact residue remains"
  lpstat -p "$QUEUE" >/dev/null 2>&1 && fail "product queue remains after uninstall"
  id _hplj1020 >/dev/null 2>&1 && fail "dedicated service account remains after uninstall"
  record "complete uninstall absence audit passed"
}

snapshot_unrelated_queues() {
  {
    lpstat -p -v -d 2>/dev/null | grep -v "$QUEUE" || true
    while read -r queue; do
      [[ -n "$queue" ]] && lpoptions -p "$queue" 2>/dev/null || true
    done < <(lpstat -p 2>/dev/null | awk -v product="$QUEUE" '$2 != product {print $2}' | LC_ALL=C sort)
  } | LC_ALL=C sort
}

cups_static_configuration_digest() {
  while IFS= read -r path; do
    case "$path" in
      /etc/cups/certs/* | /etc/cups/ppd/* | /etc/cups/printers.conf* | /etc/cups/classes.conf* | /etc/cups/subscriptions.conf*)
        continue
        ;;
    esac
    sudo shasum -a 256 "$path"
  done < <(sudo find /etc/cups -type f -print 2>/dev/null) |
    sanitize | LC_ALL=C sort | shasum -a 256 | awk '{print $1}'
}

banner "HP LJ 1020 reference Mac lifecycle validation"

stage "Validate the reference environment"
say "This run records only redacted operational evidence. No firmware, job payload, filename, username, credential, or printer serial is retained."
[[ "$(sw_vers -productVersion)" == "$EXPECTED_VERSION" ]] || fail "expected macOS $EXPECTED_VERSION"
[[ "$(sw_vers -buildVersion)" == "$EXPECTED_BUILD" ]] || fail "expected macOS build $EXPECTED_BUILD"
[[ "$(uname -m)" == arm64 ]] || fail "reference Mac is not arm64"
git -C "$ROOT" diff --quiet && git -C "$ROOT" diff --cached --quiet || fail "tracked worktree changes must be committed first"
USB_RECORD=$(ioreg -p IOUSB -r -n 'HP LaserJet 1020' -l -w0)
[[ "$(awk -F'= ' '/"idVendor"/{print $2; exit}' <<<"$USB_RECORD")" == 1008 ]] || fail "reference printer vendor identity is not 03f0"
[[ "$(awk -F'= ' '/"idProduct"/{print $2; exit}' <<<"$USB_RECORD")" == 11031 ]] || fail "reference printer product identity is not 2b17"
USB_ROW=$(awk '/kUSBSerialNumberString/{print; exit}' <<<"$USB_RECORD")
[[ -n "$USB_ROW" ]] || fail "reference printer serial identity is unavailable"
PRINTER_SERIAL_SHA=$(printf '%s' "$USB_ROW" | shasum -a 256 | awk '{print $1}')
DOCK_LOCATION=$(awk -F'= ' '/"locationID"/{print $2; exit}' <<<"$USB_RECORD")
record "environment macOS=$EXPECTED_VERSION build=$EXPECTED_BUILD architecture=arm64 sourceCommit=$SOURCE_COMMIT dependencyLockSha256=$LOCK_SHA printer=HP-LaserJet-1020 vendorProduct=03f0:2b17 serialSha256=$PRINTER_SERIAL_SHA"
sudo -v
preserve_private_firmware
create_validation_account
start_privilege_monitor

stage "Start from a clean product state"
run_recorded python3 "$INSTALLER" uninstall || fail "clean-state preview failed"
run_recorded python3 "$INSTALLER" uninstall --apply --yes || fail "could not converge to clean state"
UNRELATED_BEFORE=$(snapshot_unrelated_queues)
CUPSD_SHA_BEFORE=$(sudo shasum -a 256 /usr/sbin/cupsd | awk '{print $1}')
CUPS_CONFIG_SHA_BEFORE=$(cups_static_configuration_digest)
CUPS_LAUNCHD_SHA_BEFORE=$(shasum -a 256 /System/Library/LaunchDaemons/org.cups.cupsd.plist | awk '{print $1}')
record "clean product state established"

stage "Install and verify the dock path"
step "Keep the reference printer powered on through the UGREEN Thunderbolt 4 dock."
pause "Press Enter when the dock connection path is ready."
install_product
submit_non_admin_job

stage "Disable and reactivate"
run_recorded python3 "$INSTALLER" disable --apply --yes || fail "disable failed"
lsof -nP -iTCP:8631 -sTCP:LISTEN | grep -q . && fail "listener remains available while disabled"
run_recorded python3 "$INSTALLER" enable --apply --yes || fail "reactivation failed"
verify_installed_boundaries
record "disable/reactivate lifecycle passed"

stage "Recover interrupted and partial states"
sudo lpadmin -x "$QUEUE"
install_product
set +e
run_recorded python3 "$INTERRUPTER"
INTERRUPTED_STATUS=$?
set -e
[[ "$INTERRUPTED_STATUS" == 130 ]] || fail "uninstall did not stop at its queue-removal interruption point"
[[ -e "$INSTALL_ROOT" ]] || fail "interrupted uninstall did not retain the expected partial product state"
record "uninstall process intentionally interrupted after queue removal"
install_product
record "queue-loss partial state and interrupted uninstall converged"

stage "Complete lifecycle cycle one"
uninstall_product
LIFECYCLE_CYCLES=1

stage "Repeat two complete lifecycle cycles"
for cycle in 2 3; do
  record "lifecycle cycle $cycle started"
  install_product
  submit_non_admin_job
  uninstall_product
  LIFECYCLE_CYCLES=$cycle
  record "lifecycle cycle $cycle passed"
done

stage "Run the direct-adapter smoke path"
step "Move the powered-off reference printer from the dock to the direct USB-A-to-USB-C adapter, then power it on."
pause "Press Enter when the direct connection path is ready."
DIRECT_RECORD=$(ioreg -p IOUSB -r -n 'HP LaserJet 1020' -l -w0)
[[ "$(awk -F'= ' '/"idVendor"/{print $2; exit}' <<<"$DIRECT_RECORD")" == 1008 ]] || fail "direct-path printer vendor identity is not 03f0"
[[ "$(awk -F'= ' '/"idProduct"/{print $2; exit}' <<<"$DIRECT_RECORD")" == 11031 ]] || fail "direct-path printer product identity is not 2b17"
DIRECT_LOCATION=$(awk -F'= ' '/"locationID"/{print $2; exit}' <<<"$DIRECT_RECORD")
[[ -n "$DIRECT_LOCATION" && "$DIRECT_LOCATION" != "$DOCK_LOCATION" ]] || fail "direct path did not produce a distinct USB topology location"
DIRECT_SERIAL_ROW=$(awk '/kUSBSerialNumberString/{print; exit}' <<<"$DIRECT_RECORD")
DIRECT_SERIAL_SHA=$(printf '%s' "$DIRECT_SERIAL_ROW" | shasum -a 256 | awk '{print $1}')
[[ "$DIRECT_SERIAL_SHA" == "$PRINTER_SERIAL_SHA" ]] || fail "direct path is connected to a different printer unit"
record "direct adapter path confirmed by human action and distinct USB location"
install_product
submit_non_admin_job
uninstall_product
[[ "$(snapshot_unrelated_queues)" == "$UNRELATED_BEFORE" ]] || fail "unrelated queue inventory changed"
[[ "$(sudo shasum -a 256 /usr/sbin/cupsd | awk '{print $1}')" == "$CUPSD_SHA_BEFORE" ]] || fail "system CUPS executable changed"
[[ "$(cups_static_configuration_digest)" == "$CUPS_CONFIG_SHA_BEFORE" ]] || fail "static system CUPS configuration changed"
[[ "$(shasum -a 256 /System/Library/LaunchDaemons/org.cups.cupsd.plist | awk '{print $1}')" == "$CUPS_LAUNCHD_SHA_BEFORE" ]] || fail "system CUPS LaunchDaemon changed"
record "direct-adapter install-to-print and removal smoke passed"

stage "Seal the redacted evidence"
stop_privilege_monitor
assert_privilege_monitor
say "Inspect all four retained test pages. Enter measured maxima; do not enter notes, filenames, or identities."
say "Measure the 100 mm ruler between end ticks on every page. Scale error percent = absolute(measured millimeters - 100)."
say "Each cross center is 20 mm from both nearest paper edges. Position error = absolute(measured millimeters - 20); check both edges at all four crosses."
say "Enter the largest error across all four pages for each measurement."
if ! confirm "Do all four pages have correct count/order, no blank/partial/duplicate pages, correct orientation/media, readable fine patterns, and no clipping/corruption/density discontinuity?"; then
  fail "physical output inspection failed"
fi
ask SCALE_ERROR_PERCENT "Maximum absolute scale error percent (must be <= 1):"
[[ "$SCALE_ERROR_PERCENT" =~ ^[0-9]+([.][0-9]+)?$ ]] || fail "scale error is not numeric"
awk -v value="$SCALE_ERROR_PERCENT" 'BEGIN {exit !(value <= 1)}' || fail "scale error exceeds 1 percent"
ask MAXIMUM_FIDUCIAL_DISPLACEMENT_MM "Maximum fiducial displacement in mm (must be <= 2):"
[[ "$MAXIMUM_FIDUCIAL_DISPLACEMENT_MM" =~ ^[0-9]+([.][0-9]+)?$ ]] || fail "fiducial displacement is not numeric"
awk -v value="$MAXIMUM_FIDUCIAL_DISPLACEMENT_MM" 'BEGIN {exit !(value <= 2)}' || fail "fiducial displacement exceeds 2 mm"
remove_validation_account || fail "temporary validation account cleanup failed"
seal_run passed "all lifecycle stages and three repeated cycles passed without unexplained intermittent failure"
note "Immutable evidence: $EVIDENCE_ROOT"
if (( RESTORE_PRINTING )); then
  say "Evidence is sealed. Restoring the working personal-use installation outside the validation run."
  python3 "$INSTALLER" install --apply --yes
  import_private_firmware
fi
# Remove only this run's validated temporary copy; imported firmware stays private.
rm "$FIRMWARE_SNAPSHOT/contents"
rmdir "$FIRMWARE_SNAPSHOT"
FIRMWARE_SNAPSHOT=""
finish
