#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
SERVICE_USER="_hplj1020"
TEST_USER="_hplj1020test"
SERVICE_LABEL="com.bartekpapierski.hplj1020.lifecycle.daemon"
INSTALL_APP="/Applications/HP LJ 1020 Lifecycle Prototype.app"
STATE_ROOT="/Library/Application Support/HP-LJ-1020/State"
LOG_ROOT="/Library/Logs/HP-LJ-1020"
CAPTURE_ROOT="/Library/Application Support/HP-LJ-1020/Captured"
EVIDENCE_DIR=$(mktemp -d /private/tmp/hplj1020-lifecycle-evidence.XXXXXX)
SERVICE_ENABLED=0
APP_PATH=""

next_free_system_id() {
  local candidate
  for ((candidate=499; candidate>=450; candidate--)); do
    if ! dscacheutil -q user -a uid "$candidate" | grep -q '^name:' && \
       ! dscacheutil -q group -a gid "$candidate" | grep -q '^name:'; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  return 1
}

prototype_account_matches() {
  local account="$1" real_name="$2" uid user_gid group_gid
  uid=$(dscl . -read "/Users/$account" UniqueID 2>/dev/null | awk '{print $2}') || return 1
  user_gid=$(dscl . -read "/Users/$account" PrimaryGroupID 2>/dev/null | awk '{print $2}') || return 1
  group_gid=$(dscl . -read "/Groups/$account" PrimaryGroupID 2>/dev/null | awk '{print $2}') || return 1
  [[ "$uid" =~ ^[0-9]+$ && "$uid" -ge 450 && "$uid" -le 499 ]] || return 1
  [[ "$user_gid" == "$group_gid" ]] || return 1
  dscl . -read "/Users/$account" RealName 2>/dev/null | grep -Fqx "RealName: $real_name" || return 1
  dscl . -read "/Users/$account" IsHidden 2>/dev/null | grep -Fqx 'IsHidden: 1' || return 1
  dscl . -read "/Users/$account" UserShell 2>/dev/null | grep -Fqx 'UserShell: /usr/bin/false'
}

create_hidden_account() {
  local account="$1" real_name="$2" account_id
  if id "$account" >/dev/null 2>&1; then
    if prototype_account_matches "$account" "$real_name"; then
      return 0
    fi
    warn "Refusing to reuse existing account $account because it is not owned by this prototype."
    return 1
  fi
  if dscacheutil -q group -a name "$account" | grep -q '^name:'; then
    warn "Refusing to reuse existing group $account because its matching prototype account is absent."
    return 1
  fi
  account_id=$(next_free_system_id)
  sudo dscl . -create "/Groups/$account"
  sudo dscl . -create "/Groups/$account" PrimaryGroupID "$account_id"
  sudo dscl . -create "/Groups/$account" Password '*'
  sudo dscl . -create "/Users/$account"
  sudo dscl . -create "/Users/$account" UniqueID "$account_id"
  sudo dscl . -create "/Users/$account" PrimaryGroupID "$account_id"
  sudo dscl . -create "/Users/$account" RealName "$real_name"
  sudo dscl . -create "/Users/$account" NFSHomeDirectory /var/empty
  sudo dscl . -create "/Users/$account" UserShell /usr/bin/false
  sudo dscl . -create "/Users/$account" IsHidden 1
  sudo dscl . -create "/Users/$account" Password '*'
}

remove_hidden_account() {
  local account="$1" real_name="$2"
  if id "$account" >/dev/null 2>&1; then
    if ! prototype_account_matches "$account" "$real_name"; then
      warn "Preserving $account because it does not match the prototype account marker."
      return 0
    fi
    sudo dscl . -delete "/Users/$account"
  fi
  if dscacheutil -q group -a name "$account" | grep -q '^name:'; then
    sudo dscl . -delete "/Groups/$account"
  fi
}

banner "HP LaserJet 1020 lifecycle feasibility proof"

stage "Build the pinned ad-hoc provider"
say "This builds PAPPL 1.4.12, OpenSSL 3.6.3, and libusb 1.0.30 from verified source inputs."
say "All outputs stay in a new /private/tmp directory. No system changes happen here."
BUILD_LOG="$EVIDENCE_DIR/build.log"
"$SCRIPT_DIR/build.sh" 2>&1 | tee "$BUILD_LOG"
APP_PATH=$(sed -n 's/^APP_PATH=//p' "$BUILD_LOG" | tail -n 1)
if [[ ! -d "$APP_PATH" ]]; then
  warn "Build did not produce an app bundle."
  exit 1
fi
cp "$APP_PATH/Contents/Resources/build-manifest.txt" "$EVIDENCE_DIR/build-manifest.txt"
note "Built artifact: $APP_PATH"

stage "Create the service account and install"
say "The next step creates one hidden, non-login service account and copies the prototype to /Applications."
warn "macOS will ask for your administrator password. The wizard never reads or stores it."
if ! confirm "Create $SERVICE_USER and install the prototype?"; then
  warn "Stopped before system changes."
  exit 0
fi
create_hidden_account "$SERVICE_USER" "HP LaserJet 1020 Service"
sudo mkdir -p \
  "$STATE_ROOT/Home/Library/Application Support" \
  "$STATE_ROOT/Spool" \
  "$LOG_ROOT" \
  "$CAPTURE_ROOT"
sudo chown -R "$SERVICE_USER:$SERVICE_USER" \
  "$STATE_ROOT" "$LOG_ROOT" "$CAPTURE_ROOT"
sudo chmod -R u+rwX,go-rwx "$STATE_ROOT" "$LOG_ROOT" "$CAPTURE_ROOT"
sudo ditto "$APP_PATH" "$INSTALL_APP"
sudo chown -R root:wheel "$INSTALL_APP"
codesign --verify --deep --strict --verbose=2 "$INSTALL_APP" 2>&1 | tee "$EVIDENCE_DIR/codesign-verification.txt"
note "Installed app and private state paths."

stage "Register and approve the LaunchDaemon"
CONTROLLER="$INSTALL_APP/Contents/MacOS/hplj1020-lifecycle"
REGISTRATION_LOG="$EVIDENCE_DIR/service-registration.txt"
if "$CONTROLLER" register >"$REGISTRATION_LOG" 2>&1; then
  note "Registration call returned success."
else
  warn "Registration call failed. The exact Service Management result follows."
fi
cat "$REGISTRATION_LOG"
"$CONTROLLER" status | tee -a "$REGISTRATION_LOG"
SERVICE_STATUS=$("$CONTROLLER" status | sed -n 's/^service_status=//p')
if [[ "$SERVICE_STATUS" == "requires-approval" ]]; then
  step "System Settings will open to General → Login Items & Extensions."
  step "Approve HP LJ 1020 Lifecycle Prototype under background items."
  "$CONTROLLER" open-settings >>"$REGISTRATION_LOG" 2>&1 || true
  pause "Press Enter after approving it in System Settings."
  "$CONTROLLER" status | tee -a "$REGISTRATION_LOG"
  SERVICE_STATUS=$("$CONTROLLER" status | sed -n 's/^service_status=//p')
fi
if [[ "$SERVICE_STATUS" == "enabled" ]]; then
  SERVICE_ENABLED=1
  note "Service Management reports enabled."
else
  warn "Service is $SERVICE_STATUS. This invalidates the ad-hoc SMAppService boundary on this host."
fi

stage "Verify identity, listener, queue, and USB access"
BOUNDARY_LOG="$EVIDENCE_DIR/runtime-boundaries.txt"
if (( SERVICE_ENABLED == 0 )); then
  say "Skipped: later lifecycle boundaries are meaningless until registration and approval succeed."
  printf 'runtime_boundaries=blocked-by-service-registration\n' > "$BOUNDARY_LOG"
else
  pause "Connect and power on the reference printer through the UGREEN dock, then press Enter."
  sleep 2
  SERVICE_PID=$(pgrep -x hplj1020-pappl | head -n 1 || true)
  if [[ -z "$SERVICE_PID" ]]; then
    warn "The registered daemon is not running."
    printf 'daemon_running=false\n' | tee -a "$BOUNDARY_LOG"
  else
    ps -o user=,uid=,pid=,command= -p "$SERVICE_PID" | tee -a "$BOUNDARY_LOG"
    if /usr/sbin/lsof -nP -a -p "$SERVICE_PID" -iTCP:8631 -sTCP:LISTEN | tee -a "$BOUNDARY_LOG"; then
      printf 'listener_8631=true\n' | tee -a "$BOUNDARY_LOG"
    else
      printf 'listener_8631=false\n' | tee -a "$BOUNDARY_LOG"
      warn "The daemon is running but is not listening on TCP port 8631."
    fi
  fi

  PAPPL_CLI="$INSTALL_APP/Contents/MacOS/hplj1020-pappl"
  PAPPL_HOME="$STATE_ROOT/Home"
  run_pappl_cli() {
    sudo -u "$SERVICE_USER" env HOME="$PAPPL_HOME" \
      /bin/bash -c 'exec -a hplj1020-pappl "$@"' bash "$PAPPL_CLI" "$@"
  }
  PAPPL_READY=1
  if ! run_pappl_cli printers >/dev/null 2>&1; then
    PAPPL_READY=0
    printf 'pappl_cli_reachable=false\n' | tee -a "$BOUNDARY_LOG"
    warn "Could not reach the PAPPL service as its dedicated account."
  else
    printf 'pappl_cli_reachable=true\n' | tee -a "$BOUNDARY_LOG"
  fi
  if (( PAPPL_READY == 1 )); then
    if ! run_pappl_cli printers 2>/dev/null | grep -q Lifecycle; then
      if ! run_pappl_cli add \
        -d Lifecycle \
        -m pwg_common-300dpi-600dpi-black_1 \
        -v 'file:///Library/Application%20Support/HP-LJ-1020/Captured?ext=pwg'; then
        PAPPL_READY=0
        printf 'file_printer_created=false\n' | tee -a "$BOUNDARY_LOG"
        warn "Could not create the PAPPL file-backed test printer."
      fi
    fi
  fi

  if (( PAPPL_READY == 1 )); then
    printf 'file_printer_created=true\n' | tee -a "$BOUNDARY_LOG"
    CUPS_READY=1
    if ! sudo launchctl kickstart -k system/org.cups.cupsd; then
      CUPS_READY=0
      printf 'cups_scheduler_started=false\n' | tee -a "$BOUNDARY_LOG"
      warn "Could not start the macOS CUPS scheduler."
    fi
    if (( CUPS_READY == 1 )) && ! sudo lpadmin -p HPLJ1020Lifecycle -E \
      -v ipp://localhost:8631/ipp/print/Lifecycle -m everywhere; then
      CUPS_READY=0
      printf 'cups_queue_created=false\n' | tee -a "$BOUNDARY_LOG"
      warn "Could not create the standard macOS queue."
    fi
    if (( CUPS_READY == 1 )); then
      printf 'cups_queue_created=true\n' | tee -a "$BOUNDARY_LOG"
      if create_hidden_account "$TEST_USER" "HP LaserJet 1020 Non-Admin Test"; then
        if sudo -u "$TEST_USER" env HOME=/var/empty \
          lp -d HPLJ1020Lifecycle /usr/share/cups/data/testprint 2>&1 | \
          sed 's/request id is .*/request accepted/' | tee -a "$BOUNDARY_LOG"; then
          printf 'non_admin_submission=true\n' | tee -a "$BOUNDARY_LOG"
        else
          printf 'non_admin_submission=false\n' | tee -a "$BOUNDARY_LOG"
          warn "The non-admin print submission failed."
        fi
      else
        printf 'non_admin_submission=blocked-by-account-collision\n' | tee -a "$BOUNDARY_LOG"
      fi
      sleep 3
    fi
  fi
  CAPTURE_COUNT=$(find "$CAPTURE_ROOT" -type f | wc -l | tr -d ' ')
  printf 'captured_jobs=%s\n' "$CAPTURE_COUNT" | tee -a "$BOUNDARY_LOG"

  USB_PROBE="$INSTALL_APP/Contents/MacOS/hplj1020-usb-probe"
  USB_PROBE_LOG="$EVIDENCE_DIR/usb-probe.txt"
  if sudo -u "$SERVICE_USER" env HOME="$PAPPL_HOME" "$USB_PROBE" >"$USB_PROBE_LOG" 2>&1; then
    cat "$USB_PROBE_LOG" | tee -a "$BOUNDARY_LOG"
    printf 'privileged_helper=unnecessary\n' | tee -a "$BOUNDARY_LOG"
  elif grep -q '^usb_probe_result=claim-failed$' "$USB_PROBE_LOG"; then
    cat "$USB_PROBE_LOG" | tee -a "$BOUNDARY_LOG"
    printf 'privileged_helper=investigate-minimal\n' | tee -a "$BOUNDARY_LOG"
    warn "Dedicated-account USB claim failed. A minimal helper investigation is justified, not yet approved."
  else
    cat "$USB_PROBE_LOG" | tee -a "$BOUNDARY_LOG"
    printf 'privileged_helper=undetermined\n' | tee -a "$BOUNDARY_LOG"
    warn "USB access is undetermined because the reference printer was not discovered."
  fi
fi

stage "Preview cleanup and preserve evidence"
say "Cleanup will unregister the prototype and remove only these prototype-owned artifacts:"
step "$INSTALL_APP"
step "CUPS queue HPLJ1020Lifecycle"
step "$STATE_ROOT, $LOG_ROOT, and $CAPTURE_ROOT"
step "Local accounts $SERVICE_USER and $TEST_USER"
note "Evidence remains at $EVIDENCE_DIR."
if confirm "Unregister and remove those exact prototype artifacts now?"; then
  if [[ -x "$CONTROLLER" ]]; then
    "$CONTROLLER" unregister >>"$EVIDENCE_DIR/cleanup.txt" 2>&1 || true
  fi
  sudo launchctl bootout "system/$SERVICE_LABEL" >>"$EVIDENCE_DIR/cleanup.txt" 2>&1 || true
  sudo lpadmin -x HPLJ1020Lifecycle >/dev/null 2>&1 || true
  sudo rm -rf "$INSTALL_APP"
  sudo rm -rf "/Library/Application Support/HP-LJ-1020"
  sudo rm -rf "$LOG_ROOT"
  remove_hidden_account "$TEST_USER" "HP LaserJet 1020 Non-Admin Test"
  remove_hidden_account "$SERVICE_USER" "HP LaserJet 1020 Service"
  printf 'cleanup=completed\n' | tee -a "$EVIDENCE_DIR/cleanup.txt"
else
  warn "Cleanup skipped. The installed prototype remains on the Mac."
  SKIPPED+=("prototype cleanup")
fi

note "Return this evidence directory for review: $EVIDENCE_DIR"
finish
